-- 코드를 입력하세요
SELECT 
    YEAR(SALES_DATE) AS YEAR, 
    MONTH(SALES_DATE) AS MONTH, 
    COUNT(DISTINCT o.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT o.USER_ID) / (SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PUCHASED_RATIO
FROM USER_INFO u 
LEFT JOIN ONLINE_SALE o ON u.USER_ID = o.USER_ID
WHERE YEAR(JOINED) = 2021
GROUP BY YEAR, MONTH
HAVING YEAR IS NOT NULL
ORDER BY YEAR, MONTH;