-- 코드를 입력하세요
SELECT HISTORY_ID, 
    FLOOR(CASE
          WHEN DISCOUNT_RATE IS NULL THEN DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1)
          ELSE DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) * (1 - DISCOUNT_RATE / 100)
          END) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h ON c.CAR_ID = h.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p ON c.CAR_TYPE = p.CAR_TYPE
AND (
    (DURATION_TYPE = '90일 이상' AND (DATEDIFF(END_DATE, START_DATE) + 1) >= 90) OR
    (DURATION_TYPE = '30일 이상' AND (DATEDIFF(END_DATE, START_DATE) + 1) >= 30 AND (DATEDIFF(END_DATE, START_DATE) + 1) < 90) OR
    (DURATION_TYPE = '7일 이상' AND (DATEDIFF(END_DATE, START_DATE) + 1) >= 7 AND (DATEDIFF(END_DATE, START_DATE) + 1) < 30)
)
WHERE c.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;