-- 코드를 입력하세요
SELECT FLAVOR
FROM (
    SELECT h.FLAVOR, SUM(h.TOTAL_ORDER + j.TOTAL_ORDER) AS SUM
    FROM FIRST_HALF h JOIN JULY j ON h.FLAVOR = j.FLAVOR
    GROUP BY FLAVOR
    ORDER BY SUM DESC
    LIMIT 3
) s