-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE m JOIN REST_REVIEW r ON m.MEMBER_ID = r.MEMBER_ID
WHERE MEMBER_NAME = (
    SELECT MEMBER_NAME
    FROM MEMBER_PROFILE m JOIN REST_REVIEW r ON m.MEMBER_ID = r.MEMBER_ID
    GROUP BY MEMBER_NAME
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY REVIEW_DATE, REVIEW_TEXT